analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/.dart_tool/**"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    avoid_dynamic_calls: ignore
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_redundant_argument_values: ignore
