# This file configures the static analysis results for your project.
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
#   exclude:
#     - path/to/excluded/files/**

formatter:
  page_width: 80
  trailing_commas: preserve
