name: merchant
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  date_format: ^2.0.9
  dio: ^5.9.2
  jaspr: ^0.23.2
  jaspr_lucide: ^0.55.0
  signals: ^7.1.0
  jaspr_router: ^0.8.2
  models:
    path: ../packages/models
  validators:
    path: ../packages/validators
  api_client:
    path: ../packages/api_client
  client_repositories:
    path: ../packages/client_repositories
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.7.0
  jaspr_builder: ^0.23.2
  lints: ^6.0.0

jaspr:
  mode: client
